config/routes.rb
Rails.application.routes.draw do
  resources :competitions
  root 'home#index'
  devise_for :users, controllers: { :omniauth_callbacks => 'users/omniauth_callbacks' }

  get  '/join_competitions/:id'  => 'solutions#join_competition', as: "join_competition"
  post '/join_competitions/:id'  => 'solutions#submit_competition'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competition.rb
class Competition < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :name, presence: true, length: {minimum: 0, maximum: 100}
  validates :left_time, presence: true
  validates :participants_number, presence: true, numericality: { only_integer: true }
  validates :details, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2, :facebook, :twitter]


   def self.from_omniauth(access_token)
      data = access_token.info
      user = User.where(email: data['email']).first

      # Uncomment the section below if you want users to be created if they don't exist
      unless user
          user = User.create(email: data['email'], firstname: data['name'], password: Devise.friendly_token[0,20] )
      end
      user
  end
end

app/models/user_competition.rb
class UserCompetition < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname])
  end

  def authenticate_admin!
    if current_user.blank? || current_user.role != "admin"
        redirect_to '/'
    end
  end

end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_competition, only: [:show, :edit, :update, :destroy]

  # GET /competitions
  def index
    @competitions = Competition.all

  end

  # GET /competitions/1
  def show
    if current_user.present?
      @user_competition  = UserCompetition.where(user_id: current_user.id, competition_id: params[:id]).first
    end

    @user_competitions = UserCompetition.select("users.firstname, user_competitions.created_at, user_competitions.answer")
                                        .joins("INNER JOIN users ON users.id = user_competitions.user_id")
                                        .joins("INNER JOIN competitions ON competitions.id = user_competitions.competition_id")
                                        .where(competition_id: params[:id])
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  def create
    @competition = Competition.new(competition_params)
    if @competition.save
      redirect_to @competition, notice: 'Competition was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /competitions/1
  def update
      if @competition.update(competition_params)
        redirect_to @competition, notice: 'Competition was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /competitions/1
  def destroy
    @competition.destroy
    redirect_to competitions_url, notice: 'Competition was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:name, :image, :left_time, :participants_number, :details)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :authenticate_user!, only: [:join_competition, :submit_competition]

  # GET /join_compotition/:id
  def join_competition
    @user_competition = UserCompetition.where(:user_id => current_user.id, :competition_id => params[:id]).first
    if @user_competition.blank?
      @user_competition = UserCompetition.create!(:user_id => current_user.id, :competition_id => params[:id])
    end
  end

  # POST /join_competitions/:id
  def submit_competition
      user_competition_id = params[:id]
      answer = params[:user_competition][:answer]

      user_competition = UserCompetition.where(id: user_competition_id).first
      user_competition.update!(answer: answer)

      redirect_to "/competitions/#{user_competition.competition_id}"
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end

  def facebook
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        sign_in_and_redirect @user
        set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
      else
        flash[:error] = 'There was a problem signing you in through Facebook. Please register or try signing in later.'
        redirect_to new_user_registration_url
      end
    end

    # twitter callback
  def twitter
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        sign_in_and_redirect @user
        set_flash_message(:notice, :success, kind: 'Twitter') if is_navigational_format?
      else
        flash[:error] = 'There was a problem signing you in through Twitter. Please register or try signing in later.'
        redirect_to new_user_registration_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<div class="col-md-6">
  <%= form_with(model: competition, local: true) do |form| %>
    <% if competition.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

        <ul>
        <% competition.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :competition_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="form-group">
      <%= form.label :Deadline %>
      <%= form.date_select :left_time, id: :competition_left_time, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :participants_number %>
      <%= form.number_field :participants_number, id: :competition_participants_number, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :details, id: :competition_details, class: "form-control" %>
    </div>

    <div class="actions">
        <%= form.submit class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/competitions/edit.html.erb
<h2><center>UPDATE COMPETITION</h2>

<%= render 'form', competition: @competition %>

app/views/competitions/index.html.erb
<script>
  $(document).ready(function() {
    $('#competitions').dataTable();
  } );
</script>

<p id="notice"><%= notice %></p>

<h2><center>COMPETITIONS</h2>


<table id='competitions' class="table table-striped">

  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="/competitions" role="tab" aria-controls="pills-home" aria-selected="true">All</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="/competitions?active=1" role="tab" aria-controls="pills-profile" aria-selected="false">Active</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="/competitions?active=0" role="tab" aria-controls="pills-contact" aria-selected="false">Inactive</a>
    </li>
  </ul>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">...</div>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">...</div>
    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">...</div>
  </div>

  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Left time</th>
      <th>Participants number</th>
      <th>Created Date</th>
      <!-- <th>Details</th> -->
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= image_tag competition.image_url.to_s, width: 100, height: 100 %></td>
        <td width="200"><%= competition.name %></td>
        <td><%= Time.at((competition.left_time - DateTime.now).to_i.seconds).strftime("%d:%H:%Mminutes:%Sseconds") %></td>
        <td><%= competition.participants_number %></td>
        <td><%= competition.created_at.strftime("%Y/%m/%d %H:%M")%></td>
        <!-- <td width="400"><%= competition.details %></td> -->
        <td width="100">
          <%= link_to 'Detail', competition, class: "btn btn-info", style: "padding: 5px; color: #fff;  margin: 5px;" %> <br>
          <% if current_user.present? && current_user.role == "admin" %>
            <%= link_to 'Update', edit_competition_path(competition), class: "btn btn-info", style: "padding: 5px; color: #fff; margin: 5px;" %> <br>
            <%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", style: "padding: 5px; color: #fff; margin: 5px;" %>
          <% else %>
            <a href="/join_competitions/<%= competition.id %>", class="btn btn-info", style="padding: 5px; color: #fff; margin: 5px;">Join this competition</a> <br>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/competitions/new.html.erb
<h2><center>HOST COMPETITION</h2>

<%= render 'form', competition: @competition %>
<div class="col-sm-12">
</div>

app/views/competitions/show.html.erb
<p id="notice"><%= notice %></p>

<h2><center>COMPETITION DETAIL</h2>

<p>
  <strong>Name:</strong>
  <%= @competition.name %>
</p>

<p>
  <%= image_tag @competition.image_url.to_s, width: 100, height: 100 %>
</p>

<p>
  <strong>Left time:</strong>
  <%= Time.at((@competition.left_time - DateTime.now).to_i.seconds).strftime("%d:%H:%Mminutes:%Sseconds") %>
</p>

<p>
  <strong>Deadline</strong>
  <%= @competition.left_time.strftime("%Y/%m/%d %H:%M") %>
</p>

<p>
  <strong>Participants number:</strong>
  <%= @competition.participants_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @competition.details %>
</p>

<% if @user_competition.present? && current_user.role != "admin"%>
<p>
  <strong>My submission</strong></br>
  <%= @user_competition.answer %>
</br>
</br>
</br>
</p>
<% end %>

<% if current_user.present? && current_user.role == "admin" %>
<p>
  <strong>Participant list</strong>
</p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created Date</th>
      <th>Submission detail</th>
    </tr>
  </thead>
  <tbody>
    <% @user_competitions.each do |user_competition| %>
      <tr>
        <td><%= user_competition.firstname%></td>
        <td><%= user_competition.created_at.strftime("%Y/%m/%d %H:%M") %></td>
        <td><%= user_competition.answer %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%else%>
<a href="/join_competitions/<%= @competition.id %>" class="btn btn-info">Join this competition</a> <br>
<%end%>

app/views/home/index.html.erb
<h1 class="home-title">Unimedia E-Competition</h1>
<div class="home-detail">
Unimedia E-Competition makes it easy to build powerful online contests that convert.
Launch beautiful, branded contest microsites that can integrate into your website, or stand alone, in minutes.
With Unimedia’s flexible platform, you’ll be able to create contests that help you form powerful relationships with your customers
</div>
<div class="home-detail">
Unimedia can meet the needs of any organization, big or small.
We’ll work with you to make sure you get the most out of our flexible pricing plans.
ou’ll be amazed at how much you can do.
</div>
<div class="home-detail">
We wanted to provide organizations with a simple, intuitive and flexible application management platform.
One place where they could collect applications, co-ordinate the process, and facilitate reviews.
The response was immediate, and organizations loved it.
We remain committed to improving the tool and customer experience into the future, and providing our customers with the easiest way to collect, manage and review applications.
</div>

app/views/layouts/_footer.html.erb
  <div class="container">
      <nav class="navbar navbar-head">
      </nav>
      <nav>
        <ul class="footer">
          <li><%= link_to "Home", "/"%></li>
          <li><%= link_to "Competitions", "/competitions"%></li>
          <li><%= link_to "Our Company", "http://unimedia.mn/"%></li>
          <li><%= link_to "Contact Us", "http://unimedia.mn/#sec-6"%></li>
        </ul>
      </nav>
      <p style="display: block; margin-top: 100px;"><center>Copyright © 2018 Unimedia Solutions LLC</p>
    </div>

<style media="screen">
ul.footer {
    width: 430px;
    margin: auto;
    text-align: center;
    list-style: none;
}

ul.footer li {
  float: left;
  padding-right: 20px;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div style="text-align: center;">
        <%= image_tag('logos/logo.png', :class => 'style_logo')%><strong>E-Competition</strong>
      </div>
    </div>
    <div class="container">
      <div class="row">
         <nav class="navbar navbar-head">
           <div class="container">
          		<div class="collapse navbar-collapse" id="navbar">
          			<ul class="nav navbar-nav navbar-left">
          				<li class="active"><a href="/">Home</a></li>
          				<li><a href="/competitions">Competitions</a></li>
                  <% if current_user.present? && current_user.role =='admin'%>
                  <li><a href="/competitions/new">Host a Competition</a></li>
                  <%end%>
          			</ul>
                <ul class="nav navbar-nav navbar-right">
                  <% if current_user.present?%>
                    <li style="line-height: 4; margin-top: -1px;">Hello: <%= current_user.firstname%></li>
                    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                  <%else%>
                    <li><%= link_to "Sign in", '/users/sign_in' %></li>
                  <%end%>
                </ul>
          		</div>
          	</div>
        </nav>
      </div>
    </div>

    <div class="container">
    <%= yield %>
    </div>
    <%= render "layouts/footer"%>
    <% debug(params) if Rails.env.development?%>
  </body>
</html>

app/views/solutions/join_competition.html.erb
<%= form_for @user_competition, url: "/join_competitions/#{@user_competition.id}", method: "post" do |form| %>
  <div class="field">
      <%= form.label "submit solution" %>
      <%= form.text_area :answer, rows: 5 %>

      <div class="actions">
        <input type="submit" value="submit">
      </div>
  </div>
<% end %>